name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build
        run: cargo build --release

      - name: Package
        run: iscc installer.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v7
        with:
          name: windows-installer
          path: Output/*.exe